### ISSUE TITLE
Consider widen the content area

### ISSUE THREAD

**Issue by PahudPlus** [milvus-io/www.milvus.io#137]
Or make a table self-adaptive. Either way is fine. 

![image](https://user-images.githubusercontent.com/64403786/85282379-37224480-b4be-11ea-8b47-d6660dfa8122.png)

**Comment by PahudPlus** [comment]
@shanghaikid

**Comment by shanghaikid** [comment]
wont fix. The space of the table view is limited, you can use another way to express this kind of thing.  For example, code view.
