### ISSUE TITLE
You may consider adding redirecting mechanism to some legacy pages.

### ISSUE THREAD

**Issue by PahudPlus** [milvus-io/www.milvus.io#192]
The naming of many pages are really awkward. For example, data_manage.md is about managing metadata. 

I still dare *not* change the name of such pages in order not to create broken links. 

Please work with your writing team to consider adding a redirecting mechanism, where you can redirect access requests to certain web pages to the correct pages.

**Comment by shanghaikid** [comment]
current redirect mechanism is :

    rewrite ^/docs/guides/get_started/install_milvus/(.*).md$ /docs/$1.md permanent;
    rewrite ^/docs/guides/(.*).md$ /docs/$1.md permanent;
    rewrite ^/docs/reference/(.*).md$ /docs/$1.md permanent;
    rewrite ^/docs/about_milvus/(.*).md$ /docs/$1.md permanent;
    rewrite ^/docs/faq/(.*).md$ /docs/$1.md permanent;

Any missing ?

**Comment by PahudPlus** [comment]
Greate you have a redirecting mechanism in place. So, I'll let you know once I changed the name of a document.
