### ISSUE TITLE
io page error with ！

### ISSUE THREAD

**Issue by ABNER-1** [milvus-io/www.milvus.io#20]
![Uploading 屏幕快照 2019-09-17 上午10.58.59.png…]()
maybe here should use English !

**Comment by jielinxu** [comment]
Hi ABNER-1, thanks for your comment. Do you mean there's an image that's not loaded in the Doc? Could you provide more details such as on which page the image is, so we can better look into it.

**Comment by ABNER-1** [comment]
You have fixed it.
