### ISSUE TITLE
Add a banner for promoting milvus events

### ISSUE THREAD

**Issue by PahudPlus** [milvus-io/www.milvus.io#259]
Example: https://www.vonage.com/communications-apis/video/

Requirements:

1: The banner should be designed in a way to accommodate multiple lines. 
2: Set up a folder in the zilliztech/milvus repo for the tech writers to put in the promotional contents. 
3: After the user clicks x, the banner disappears.

**Comment by zyyerin** [comment]
![image](https://user-images.githubusercontent.com/16808903/94386045-4679f380-0179-11eb-8d73-a0b9318718f6.png)

Future events can be published in Milvus doc as **an event note**.
Requirement 1&2 will be met.

**Comment by PahudPlus** [comment]
Agreed.
