### ISSUE TITLE
Replace icon-5.png with the latest version

### ISSUE THREAD

**Issue by yamasite** [milvus-io/www.milvus.io#26]
### Problem description
icon-5.png is not the latest.

### Proposed change
Replace icon-5.png with the latest version:

![icon-5](https://user-images.githubusercontent.com/10089260/67371120-6fc7f200-f5ae-11e9-82b1-99ecfd418501.png)

Please apply this change to both the English version and the Chinese version.

**Comment by shanghaikid** [comment]
fixed in 2d055b0
