### ISSUE TITLE
It may seem better

### ISSUE THREAD

**Issue by minghust** [milvus-io/www.milvus.io#29]
![m](https://user-images.githubusercontent.com/17786148/68115813-3ab78a00-ff34-11e9-920e-3b1de2db72bc.png)

**Comment by minghust** [comment]
Also, there is a bug when putting mouse on WeChat. (Windows chrome)

**Comment by shanghaikid** [comment]
After talked with our designer, we may keep the github badge on the first screen for better exposure. Thanks.
