### ISSUE TITLE
Images not displayed in Monitoring and Alerting topic in Milvus Docs

### ISSUE THREAD

**Issue by jielinxu** [milvus-io/www.milvus.io#31]
The paths of the pics are correct, yet the pics are not displayed on the website.[https://www.milvus.io/docs/en/userguide/monitor/](url)

**Comment by shanghaikid** [comment]
https://docusaurus.io/docs/en/doc-markdown#linking-to-images-and-other-assets 

we use facebook's docusaurus as site builder, it seems  no way to support relative path , we are considering other site builders, but right now, please change path in  docs, thanks.
